---
parent: "api_v1_system-settings"
name: "api_v1_system-settings_post_anonymous_invalid"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings"
method: "POST"
auth: "NONE"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode == 401"
tags:
- "V1"
authors:
- "FX Bot"
inactive: false
